def inforComuns(comum):
    igrejas = {
        'Alto São João':[
            'Daniel Júlio Santos Gomes',
            'Antônio Carlos Gomes Lima',
            'Carlos Gonçalves Gomes',
            'img/semImagem.png',
            'https://goo.gl/maps/HbvMS2oXkz6R3s9P9'
        ],
        'Carmelo':['', '', '', 'img/semImagem.png', ''],
        'Central':['', '', '', 'img/central.jpeg', ''],
        'Cidade Indsutrial':['', '', '', 'img/semImagem.png', ''],
        'José Carlos de Lima':['', '', '', 'img/semImagem.png', ''],
        'Delfino':['', '', '', 'img/delfino.jpeg', ''],
        'Edgar Pereira':['', '', '', 'img/edgar.jpeg', ''],
        'Esplanada':['', '', '', 'img/esplanada.jpeg', ''],
        'Independência':['', '', '', 'img/independencia.jpeg', ''],
        'Interlagos':['', '', '', 'img/interlagos.jpeg', ''],
        'Jaraguá':['', '', '', 'img/jaragua.jpeg', ''],
        'Jd Alegre':['', '', '', 'img/facela.jpeg', ''],
        'Jd Alvorada':['', '', '', 'img/semImagem.png', ''],
        'Jd Brasil':['', '', '', 'img/semImagem.png', ''],
        'Jd Eldorado':['', '', '', 'img/eldorado.jpg', ''],
        'Jd Primavera':['', '', '', 'img/primavera.jpg', ''],
        'Major Prates':['', '', '', 'img/major.jpg', ''],
        'Maracanã':['', '', '', 'img/semImagem.png', ''],
        'Monte Sião':['', '', '', 'img/monteSiao.jpg', ''],
        'Morrinhos':['', '', '', 'img/morrinhos.jpg', ''],
        'Nova América':['', '', '', 'img/semImagem.png', ''],
        'Planalto':['', '', '', 'img/semImagem.png', ''],
        'Renascença':['', '', '', 'img/renascenca.jpg', ''],
        'Roxo Verde':['', '', '', 'img/roxo.jpg', ''],
        # --------------------------------------------------------
        'Sagrada Família':['', '', '', 'img/semImagem.png', ''],
        'Santa Rafaela':['', '', '', 'img/semImagem.png', ''],
        'Santo Amaro':['', '', '', 'img/semImagem.png', ''],
        'Santo Antônio II':['', '', '', 'img/semImagem.png', ''],
        'São Judas':['', '', '', 'img/semImagem.png', ''],
        'Vila Anália':['', '', '', 'img/semImagem.png', ''],
        'Vila Antônio Narciso':['', '', '', 'img/semImagem.png', ''],
        'Vila Atlântida':['', '', '', 'img/semImagem.png', ''],
        'Vila Áurea II':['', '', '', 'img/semImagem.png', ''],
        'Castelo Branco':['', '', '', 'img/semImagem.png', ''],
        'Vila Oliveira':['', '', '', 'img/semImagem.png', ''],
        'Vila Sion':['', '', '', 'img/semImagem.png', ''],
        'Village do Lago':['', '', '', 'img/semImagem.png', ''],
    }
    
    return igrejas[comum]